// md read
export const SHOW_MD_REQUEST_BEGIN = 'SHOW_MD_REQUEST_BEGIN'
export const SHOW_MD_REQUEST_FAILURE = 'SHOW_MD_REQUEST_FAILURE'
export const SHOW_MD_REQUEST_SUCCESS = 'SHOW_MD_REQUEST_SUCCESS'

// md write
export const SAVE_MD_REQUEST_BEGIN = 'SAVE_MD_REQUEST_BEGIN'
export const SAVE_MD_REQUEST_FAILURE = 'SAVE_MD_REQUEST_FAILURE'
export const SAVE_MD_REQUEST_SUCCESS = 'SAVE_MD_REQUEST_SUCCESS'
