// md read
export const SHOW_MD_REQUEST_BEGIN = 'SHOW_MD_REQUEST_BEGIN'
export const SHOW_MD_REQUEST_FAILURE = 'SHOW_MD_REQUEST_FAILURE'
export const SHOW_MD_REQUEST_SUCCESS = 'SHOW_MD_REQUEST_SUCCESS'